apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
  labels:
    app: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
      version: blue
  template:
    metadata:
      labels:
        app: boardgame
        version: blue
    spec:
      containers:
      - name: boardgame
        image: anithapatcha/springboot:blue
        ports:
        - containerPort: 8080