apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
spec:
  selector:
    app: boardgame
    version: blue  # Change to 'green' when switching to the green deployment
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080